server:
  port: 10002

#服务发现客户端
eureka:
  instance:
    #向Eureka注册时，是否使用IP地址+端口号作为服务实例的唯一标识。推荐设置为true
    prefer-ip-address: true

    #============分界线================
    #以下为基本不需要配置的属性，属性的值为默认值

    #服务续约的调用时间间隔，默认30秒
    lease-renewal-interval-in-seconds: 30
    #服务失效的时间，默认90秒
    lease-expiration-duration-in-seconds: 90
    #非安全的通信端口号
    non-secure-port: 80
    #安全的通信端口号
    secure-port: 443
    #是否启用非安全的通信端口号
    non-secure-port-enabled: true
    #是否启用安全的通信端口号
    secure-port-enabled: false

  client:
    #是否将自身的实例信息注册到Eureka服务端
    register-with-eureka: true
    #是否拉取并缓存其他服务注册表副本到本地
    fetch-registry: true
    #注册到哪个Eureka服务实例
    service-url:
      defaultZone: http://localhost:8761/eureka/



spring:
  application:
    name: rayv-mongodb
  #datasource:
        #driverClassName: com.mysql.jdbc.Driver
        #url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&characterEncoding=UTF-8
        #username: root
        #password: root
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/test
      #uri: mongodb://${mongodb.host}:${mongodb.port}/${cas.service.registry.mongo.db}